"""add_chunk_business_key

Revision ID: da2eaece515d
Revises: 77027eb88884
Create Date: 2026-05-12 13:39:23.969183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da2eaece515d"
down_revision: str | None = "77027eb88884"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("chunk_business_key", sa.String(length=512), nullable=False))
    op.create_index(
        op.f("ix_chunks_chunk_business_key"), "chunks", ["chunk_business_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_chunk_business_key"), table_name="chunks")
    op.drop_column("chunks", "chunk_business_key")
    # ### end Alembic commands ###
